[build]
  cmd = "go build -o ./tmp/main.exe ./cmd/main.go"
  bin = "./tmp/main.exe"
  include_ext = ["go"]
  exclude_dir = ["tmp", "vendor"]
  delay = 500

[log]
  time = false

[misc]
  clean_on_exit = true
